---
# tasks file for while_true_do.app_ansible

- name: Manage Ansible Packages
  package:
    name: "{{ wtd_app_ansible_package }}"
    state: "{{ wtd_app_ansible_package_state }}"
  become: true
  tags:
    - package
    - ansible
    - development
    - system
